networks:
  monitor-net:
    driver: bridge

services:
  poifier-client:
    container_name: poifier-client
    build:
      context: ./poifier
    networks:
       - monitor-net
    restart: unless-stopped
    tty: true
    volumes:
      - ./configs:/root/configs/ 
    command: 
      - '--poifier-token=${TOKEN}'
      - '--subgraph-endpoint=${SUBGRAPH_ENDPOINT}'
      - '--graph-node-status-endpoint=${GRAPH_NODE}'
      - '--poifier-server=${POI_SERVER}'
      - '--mnemonic=${MNEMONIC}'
      - '--indexer-address=${INDEXER_ADDRESS}'
      - '--graph-node-config=/root/configs/config.toml'
      - '--epoch-subgraph-endpoint=https://api.thegraph.com/subgraphs/name/graphprotocol/goerli-epoch-block-oracle'
      - '--poifier-token-network=goerli'
