[store]

[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres-graph:5432/graph-node"
pool_size = 10

[chains]
ingestor = "index_node_0"

[chains.goerli]
shard = "primary"
provider = [{ label = "goerli-1", url = "http://", features = [ "archive", "traces" ] }]

[chains.gnosis]
shard = "primary"
provider = [{ label = "gnosis-1", url = "http://", features = [ "archive", "traces" ] }]

[deployment]

[[deployment.rule]]
match = { network = "gnosis" }
indexers = [ "index_node_1" ]

[[deployment.rule]]
indexers = [ "index_node_0" ]

[general]
query = "query_node_0"
